version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:942605225521:task-definition/pod-3-return-order-payment-process-td:1"
        LoadBalancerInfo:
          ContainerName: "mfpe-payment-module"
          ContainerPort: "8082"
        PlatformVersion: "LATEST"
